databases:
  - name: herberry-db
    databaseName: herberry
    user: herberry_user
    region: frankfurt
    plan: free

services:
  - type: web
    name: herberry
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:$PORT"
    healthCheckPath: /admin/login/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: herberry-db
          property: connectionString
      - key: SECRET_KEY
        value: django-insecure-p+w$7x@2m9^k#8n!r&f*3z$v@h+9j%k6l!m&p*r+t=w$7x
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: API_VERSION
        value: v1
      - key: API_TITLE
        value: Herberry API
      - key: API_DESCRIPTION
        value: Fresh Fruits & Vegetables Delivery Platform
      - key: USE_REDIS
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4