# Generated by Django 4.2.24 on 2025-10-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Oluşturuldu'), ('paid', 'Ödendi'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='created', max_length=20)),
                ('payment_provider', models.CharField(choices=[('cod', 'Kapıda Ödeme'), ('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi')], default='cod', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('shipping_cents', models.PositiveIntegerField(default=0)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('vat_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('gr', 'Gram'), ('lt', 'Litre'), ('adet', 'Adet'), ('paket', 'Paket')], max_length=10)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('line_total_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sku')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
